name: BuildAndTest

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, macos-13, ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Add requirements
      run: python -m pip install --upgrade setuptools pybind11>=2.12.0 cibuildwheel .[test]

    - name: Build Packages
      run: cibuildwheel --output-dir "dist"
      env:
        CIBW_SKIP: "cp314t-* cp314-* pp*win*"

  build_sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Add requirements
      run: python -m pip install --upgrade setuptools pybind11>=2.12.0 .[test]

    - name: Build Source Distribution
      run: python setup.py sdist
